#!/bin/bash

# Force recompile
echo "Compiling..."
rm -f susy_hmc
g++ -O3 *.cpp -o susy_hmc -llapack -lblas

# Set up parameters file same as in.SU2.hmc_pg for parallel code 
echo "3       0      1    1.0     0.3  0.025  1       41" > parameters
echo "SWEEPS  THERM  GAP  LAMBDA  MU   DT     READIN  SEED" >> parameters

# Run
echo "Running..."
ts=$(date +%s%N)
./susy_hmc &> test.out
t=$((($(date +%s%N) - $ts)/1000000))
echo -e "\nRuntime: $t msec" >> test.out

# Compare against reference output
d="`diff -I'Runtime' test.ref test.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "test.ref and test.out differ:"
  echo "$d"
else
  echo "PASS: susy_hmc reproduces reference output"
fi

# Clean up clutter
rm -f data dump eigen hmc_test lines parameters pfaffian scalar
